services:
  - type: web
    name: processflow-app
    env: node
    repo: https://github.com/your-username/processflow-app
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: processflow-db
          property: connectionString
    healthCheckPath: /
    
  - type: postgres
    name: processflow-db
    databaseName: processflow
    user: processflow_user
    plan: free
    autoDeploy: true